apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  type: ClusterIP  # Keep it as ClusterIP for internal communication
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  # Exposed port
      targetPort: 4173  # Port on the frontend container
